//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MainEnterpriseProject.Models.Domain
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DataBase : DbContext
    {
        public DataBase()
            : base("name=DataBase")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Tab_comments> Tab_comments { get; set; }
        public virtual DbSet<Tab_mail> Tab_mail { get; set; }
        public virtual DbSet<tab_products> tab_products { get; set; }
        public virtual DbSet<Tab_users> Tab_users { get; set; }
        public virtual DbSet<Tbl_Address> Tbl_Address { get; set; }
        public virtual DbSet<Tbl_AlbumCart> Tbl_AlbumCart { get; set; }
        public virtual DbSet<Tbl_AlbumFactorItem> Tbl_AlbumFactorItem { get; set; }
        public virtual DbSet<Tbl_Banner> Tbl_Banner { get; set; }
        public virtual DbSet<Tbl_Confectionary> Tbl_Confectionary { get; set; }
        public virtual DbSet<Tbl_ConfectioneryUserImage> Tbl_ConfectioneryUserImage { get; set; }
        public virtual DbSet<Tbl_Credit> Tbl_Credit { get; set; }
        public virtual DbSet<Tbl_CustomizationFood> Tbl_CustomizationFood { get; set; }
        public virtual DbSet<Tbl_Floriest> Tbl_Floriest { get; set; }
        public virtual DbSet<Tbl_FloristUserImage> Tbl_FloristUserImage { get; set; }
        public virtual DbSet<Tbl_Flower> Tbl_Flower { get; set; }
        public virtual DbSet<Tbl_FlowerComment> Tbl_FlowerComment { get; set; }
        public virtual DbSet<Tbl_FlowerOrder> Tbl_FlowerOrder { get; set; }
        public virtual DbSet<Tbl_FlowerOrderItem> Tbl_FlowerOrderItem { get; set; }
        public virtual DbSet<Tbl_FlowerReservationFactor> Tbl_FlowerReservationFactor { get; set; }
        public virtual DbSet<Tbl_FlowerReservationFactorList> Tbl_FlowerReservationFactorList { get; set; }
        public virtual DbSet<Tbl_FlowerShoppingCart> Tbl_FlowerShoppingCart { get; set; }
        public virtual DbSet<Tbl_FoodAlbume> Tbl_FoodAlbume { get; set; }
        public virtual DbSet<Tbl_FoodItemGroup> Tbl_FoodItemGroup { get; set; }
        public virtual DbSet<Tbl_FoodOption> Tbl_FoodOption { get; set; }
        public virtual DbSet<Tbl_FoodReservationFactor> Tbl_FoodReservationFactor { get; set; }
        public virtual DbSet<Tbl_FoodReservationFactorList> Tbl_FoodReservationFactorList { get; set; }
        public virtual DbSet<Tbl_Menu> Tbl_Menu { get; set; }
        public virtual DbSet<Tbl_OptionCart> Tbl_OptionCart { get; set; }
        public virtual DbSet<Tbl_OptionFactorItem> Tbl_OptionFactorItem { get; set; }
        public virtual DbSet<Tbl_OrderFactor> Tbl_OrderFactor { get; set; }
        public virtual DbSet<Tbl_OrderFactorItem> Tbl_OrderFactorItem { get; set; }
        public virtual DbSet<Tbl_PacketCart> Tbl_PacketCart { get; set; }
        public virtual DbSet<Tbl_PacketingFactorItem> Tbl_PacketingFactorItem { get; set; }
        public virtual DbSet<Tbl_Packing> Tbl_Packing { get; set; }
        public virtual DbSet<Tbl_ResPrintFactor> Tbl_ResPrintFactor { get; set; }
        public virtual DbSet<Tbl_ResPrintItem> Tbl_ResPrintItem { get; set; }
        public virtual DbSet<Tbl_ResReservationFactor> Tbl_ResReservationFactor { get; set; }
        public virtual DbSet<Tbl_ResReservationFactorItem> Tbl_ResReservationFactorItem { get; set; }
        public virtual DbSet<Tbl_ResTables> Tbl_ResTables { get; set; }
        public virtual DbSet<Tbl_Restaurant> Tbl_Restaurant { get; set; }
        public virtual DbSet<Tbl_RestaurantImage> Tbl_RestaurantImage { get; set; }
        public virtual DbSet<Tbl_ShoppingCart> Tbl_ShoppingCart { get; set; }
        public virtual DbSet<Tbl_SweetOrderFactor> Tbl_SweetOrderFactor { get; set; }
        public virtual DbSet<Tbl_SweetOrderFactorItem> Tbl_SweetOrderFactorItem { get; set; }
        public virtual DbSet<Tbl_SweetReservationFactor> Tbl_SweetReservationFactor { get; set; }
        public virtual DbSet<Tbl_SweetReservationFactorList> Tbl_SweetReservationFactorList { get; set; }
        public virtual DbSet<Tbl_Sweets> Tbl_Sweets { get; set; }
        public virtual DbSet<Tbl_SweetsComment> Tbl_SweetsComment { get; set; }
        public virtual DbSet<Tbl_SweetsShoppingCart> Tbl_SweetsShoppingCart { get; set; }
        public virtual DbSet<Tbl_UserImages> Tbl_UserImages { get; set; }
        public virtual DbSet<Tbl_Loading> Tbl_Loading { get; set; }
        public virtual DbSet<Tbl_TempOrder> Tbl_TempOrder { get; set; }
    }
}
