//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MainEnterpriseProject.Models.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tab_comments
    {
        public int id { get; set; }
        public int product_id { get; set; }
        public string name { get; set; }
        public string email { get; set; }
        public string ip { get; set; }
        public string text { get; set; }
        public System.DateTime data { get; set; }
        public bool confirm { get; set; }
        public bool read { get; set; }
        public int parent_id { get; set; }
        public int cm_like { get; set; }
        public int cm_dislike { get; set; }
        public string phone { get; set; }
        public int Stars { get; set; }
    }
}
