//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MainEnterpriseProject.Models.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tab_users
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Tab_users()
        {
            this.tab_products = new HashSet<tab_products>();
            this.Tbl_Address = new HashSet<Tbl_Address>();
            this.Tbl_Credit = new HashSet<Tbl_Credit>();
            this.Tbl_OrderFactor = new HashSet<Tbl_OrderFactor>();
            this.Tbl_Restaurant = new HashSet<Tbl_Restaurant>();
            this.Tbl_ShoppingCart = new HashSet<Tbl_ShoppingCart>();
        }
    
        public int id { get; set; }
        public string email { get; set; }
        public string password { get; set; }
        public string access { get; set; }
        public string name { get; set; }
        public string image { get; set; }
        public bool enable { get; set; }
        public string mob_phone { get; set; }
        public string ncode { get; set; }
        public string home_phone { get; set; }
        public string birth_date { get; set; }
        public string sex { get; set; }
        public string home_address { get; set; }
        public string IMEI { get; set; }
        public Nullable<bool> SMS_Enable { get; set; }
        public string activeCode { get; set; }
        public string description { get; set; }
        public string SNumber { get; set; }
        public string Family { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tab_products> tab_products { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tbl_Address> Tbl_Address { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tbl_Credit> Tbl_Credit { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tbl_OrderFactor> Tbl_OrderFactor { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tbl_Restaurant> Tbl_Restaurant { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tbl_ShoppingCart> Tbl_ShoppingCart { get; set; }
    }
}
