//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MainEnterpriseProject.Models.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_SweetOrderFactor
    {
        public int ID { get; set; }
        public int ConfectioneryID { get; set; }
        public string UserEmail { get; set; }
        public string OrderStatus { get; set; }
        public System.DateTime Date { get; set; }
        public System.TimeSpan Time { get; set; }
        public int AddresID { get; set; }
        public string Comment { get; set; }
        public string Weight { get; set; }
    }
}
