//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MainEnterpriseProject.Models.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_FoodOption
    {
        public int ID { get; set; }
        public int FoodID { get; set; }
        public int OptionID { get; set; }
    
        public virtual Tbl_CustomizationFood Tbl_CustomizationFood { get; set; }
    }
}
