//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MainEnterpriseProject.Models.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_FoodReservationFactor
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Tbl_FoodReservationFactor()
        {
            this.Tbl_FoodReservationFactorList = new HashSet<Tbl_FoodReservationFactorList>();
        }
    
        public int ID { get; set; }
        public int ResID { get; set; }
        public string UserEmail { get; set; }
        public string Date { get; set; }
        public string Time { get; set; }
        public string OrderTyoe { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tbl_FoodReservationFactorList> Tbl_FoodReservationFactorList { get; set; }
    }
}
