//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MainEnterpriseProject.Models.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_SweetReservationFactor
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Tbl_SweetReservationFactor()
        {
            this.Tbl_SweetReservationFactorList = new HashSet<Tbl_SweetReservationFactorList>();
        }
    
        public int ID { get; set; }
        public int ConfectionaryID { get; set; }
        public string UserEmail { get; set; }
        public string Date { get; set; }
        public string Time { get; set; }
        public string OrderTyoe { get; set; }
        public string OrderWeight { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tbl_SweetReservationFactorList> Tbl_SweetReservationFactorList { get; set; }
    }
}
