//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MainEnterpriseProject.Models.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_ResPrintItem
    {
        public int Counter { get; set; }
        public string Name { get; set; }
        public string OrderDate { get; set; }
        public string OrderTime { get; set; }
        public string OrderPrice { get; set; }
        public string SNumber { get; set; }
        public int ID { get; set; }
    }
}
