//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MainEnterpriseProject.Models.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_ResPrintFactor
    {
        public string StartDate { get; set; }
        public string EndDate { get; set; }
        public string ResUserName { get; set; }
        public string ResName { get; set; }
        public int ID { get; set; }
        public string TotalPrice { get; set; }
    }
}
