//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MainEnterpriseProject.Models.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_Address
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Tbl_Address()
        {
            this.Tbl_OrderFactor = new HashSet<Tbl_OrderFactor>();
        }
    
        public int ID { get; set; }
        public string userEmail { get; set; }
        public string Address { get; set; }
        public string addressType { get; set; }
        public string addressLatLng { get; set; }
        public string apartmentName { get; set; }
        public string Floor { get; set; }
        public string Unit { get; set; }
    
        public virtual Tab_users Tab_users { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tbl_OrderFactor> Tbl_OrderFactor { get; set; }
    }
}
