//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MainEnterpriseProject.Models.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_Credit
    {
        public int ID { get; set; }
        public int Credit { get; set; }
        public System.DateTime Date { get; set; }
        public string Time { get; set; }
        public string UserEmail { get; set; }
        public string TransactionCode { get; set; }
        public string RootUser { get; set; }
    
        public virtual Tab_users Tab_users { get; set; }
    }
}
