//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MainEnterpriseProject.Models.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_Confectionary
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Tbl_Confectionary()
        {
            this.Tbl_Sweets = new HashSet<Tbl_Sweets>();
        }
    
        public int ID { get; set; }
        public string CName { get; set; }
        public string CAddress { get; set; }
        public string CPhone { get; set; }
        public string CLatLng { get; set; }
        public string userEmail { get; set; }
        public string CImage { get; set; }
        public string CBusinessLicense { get; set; }
        public bool CEnable { get; set; }
        public double CPoint { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tbl_Sweets> Tbl_Sweets { get; set; }
    }
}
