//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MainEnterpriseProject.Models.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_Flower
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Tbl_Flower()
        {
            this.Tbl_FlowerComment = new HashSet<Tbl_FlowerComment>();
            this.Tbl_FlowerOrderItem = new HashSet<Tbl_FlowerOrderItem>();
            this.Tbl_FlowerReservationFactorList = new HashSet<Tbl_FlowerReservationFactorList>();
            this.Tbl_FlowerShoppingCart = new HashSet<Tbl_FlowerShoppingCart>();
        }
    
        public int ID { get; set; }
        public string FlwName { get; set; }
        public string FlwPrice { get; set; }
        public string FlwColor { get; set; }
        public string FlwType { get; set; }
        public int FlorestID { get; set; }
        public string FlwMaintenance { get; set; }
        public string FlwImage { get; set; }
    
        public virtual Tbl_Floriest Tbl_Floriest { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tbl_FlowerComment> Tbl_FlowerComment { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tbl_FlowerOrderItem> Tbl_FlowerOrderItem { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tbl_FlowerReservationFactorList> Tbl_FlowerReservationFactorList { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tbl_FlowerShoppingCart> Tbl_FlowerShoppingCart { get; set; }
    }
}
