//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MainEnterpriseProject.Models.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_CustomizationFood
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Tbl_CustomizationFood()
        {
            this.Tbl_FoodOption = new HashSet<Tbl_FoodOption>();
            this.Tbl_OptionCart = new HashSet<Tbl_OptionCart>();
        }
    
        public int ID { get; set; }
        public string foodItem { get; set; }
        public int itemPrice { get; set; }
        public int itemGroupID { get; set; }
        public bool Used { get; set; }
    
        public virtual Tbl_FoodItemGroup Tbl_FoodItemGroup { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tbl_FoodOption> Tbl_FoodOption { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tbl_OptionCart> Tbl_OptionCart { get; set; }
    }
}
