//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MainEnterpriseProject.Models.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_FloristUserImage
    {
        public int ID { get; set; }
        public string ImageName { get; set; }
        public string UserEmail { get; set; }
        public int FloristID { get; set; }
        public string Text { get; set; }
    
        public virtual Tbl_Floriest Tbl_Floriest { get; set; }
    }
}
