//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MainEnterpriseProject.Models.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_Sweets
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Tbl_Sweets()
        {
            this.Tbl_SweetOrderFactorItem = new HashSet<Tbl_SweetOrderFactorItem>();
            this.Tbl_SweetsComment = new HashSet<Tbl_SweetsComment>();
            this.Tbl_SweetsShoppingCart = new HashSet<Tbl_SweetsShoppingCart>();
        }
    
        public int ID { get; set; }
        public string S_Name { get; set; }
        public string S_Type { get; set; }
        public string S_Price { get; set; }
        public string S_Description { get; set; }
        public int ConfectionaryID { get; set; }
        public string SImage { get; set; }
    
        public virtual Tbl_Confectionary Tbl_Confectionary { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tbl_SweetOrderFactorItem> Tbl_SweetOrderFactorItem { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tbl_SweetsComment> Tbl_SweetsComment { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tbl_SweetsShoppingCart> Tbl_SweetsShoppingCart { get; set; }
    }
}
