//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MainEnterpriseProject.Models.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_OrderFactor
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Tbl_OrderFactor()
        {
            this.Tbl_OrderFactorItem = new HashSet<Tbl_OrderFactorItem>();
        }
    
        public int ID { get; set; }
        public int ResID { get; set; }
        public string OrderStatus { get; set; }
        public System.TimeSpan Time { get; set; }
        public string UserEmail { get; set; }
        public int AddressID { get; set; }
        public string Comment { get; set; }
        public System.DateTime Date { get; set; }
        public Nullable<bool> Credit { get; set; }
        public Nullable<bool> Delivery { get; set; }
        public string CreditAmount { get; set; }
        public string ReceveTime { get; set; }
    
        public virtual Tab_users Tab_users { get; set; }
        public virtual Tbl_Address Tbl_Address { get; set; }
        public virtual Tbl_Restaurant Tbl_Restaurant { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tbl_OrderFactorItem> Tbl_OrderFactorItem { get; set; }
    }
}
