//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MainEnterpriseProject.Models.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_SweetOrderFactorItem
    {
        public int ID { get; set; }
        public int SweetsID { get; set; }
        public int FactorID { get; set; }
    
        public virtual Tbl_Sweets Tbl_Sweets { get; set; }
    }
}
