//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MainEnterpriseProject.Models.Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_AlbumCart
    {
        public int ID { get; set; }
        public int AlbumID { get; set; }
        public int ShoppingCartID { get; set; }
    
        public virtual Tbl_FoodAlbume Tbl_FoodAlbume { get; set; }
    }
}
